### ISSUE TITLE
Cannot target netcore2.0

### ISSUE THREAD

**Issue by wli3** [natemcmaster/DotNetGlobalTool#1]
https://github.com/dotnet/cli/issues/9073#issuecomment-381706695

https://github.com/natemcmaster/DotNetGlobalTool/blob/master/src/McMaster.DotNet.GlobalTool.Templates/content/GlobalTool-CSharp/My.Tool.csproj#L7

netcoreapp2.0 does not have new AppHost support(able to find runtime on programfiles).

**Comment by natemcmaster** [comment]
I'm not going to change the templates. This appears to be a bug in the CLI itself. You should support netcoreapp2.0 console apps. This worked in preview1.
